=== invopop/gobl/data/schemas/bill/order.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://gobl.org/draft-0/bill/order",
  "$ref": "#/$defs/Order",
  "$defs": {
    "Order": {
      "properties": {
        "$regime": {
          "$ref": "https://gobl.org/draft-0/l10n/tax-country-code",
          "oneOf": [
            {
              "const": "AE",
              "title": "United Arab Emirates"
            },
            {
              "const": "AT",
              "title": "Austria"
            },
            {
              "const": "BE",
              "title": "Belgium"
            },
            {
              "const": "BR",
              "title": "Brazil"
            },
            {
              "const": "CA",
              "title": "Canada"
            },
            {
              "const": "CH",
              "title": "Switzerland"
            },
            {
              "const": "CO",
              "title": "Colombia"
            },
            {
              "const": "DE",
              "title": "Germany"
            },
            {
              "const": "EL",
              "title": "Greece"
            },
            {
              "const": "ES",
              "title": "Spain"
            },
            {
              "const": "FR",
              "title": "France"
            },
            {
              "const": "GB",
              "title": "United Kingdom"
            },
            {
              "const": "IN",
              "title": "India"
            },
            {
              "const": "IT",
              "title": "Italy"
            },
            {
              "const": "MX",
              "title": "Mexico"
            },
            {
              "const": "NL",
              "title": "The Netherlands"
            },
            {
              "const": "PL",
              "title": "Poland"
            },
            {
              "const": "PT",
              "title": "Portugal"
            },
            {
              "const": "SE",
              "title": "Sweden"
            },
            {
              "const": "US",
              "title": "United States of America"
            }
          ],
          "title": "Tax Regime"
        },
        "$addons": {
          "items": {
            "$ref": "https://gobl.org/draft-0/cbc/key",
            "oneOf": [
              {
                "const": "br-nfse-v1",
                "title": "Brazil NFS-e 1.X"
              },
              {
                "const": "co-dian-v2",
                "title": "Colombia DIAN UBL 2.X"
              },
              {
                "const": "de-xrechnung-v3",
                "title": "German XRechnung 3.X"
              },
              {
                "const": "de-zugferd-v2",
                "title": "German ZUGFeRD 2.X"
              },
              {
                "const": "es-facturae-v3",
                "title": "Spain FacturaE"
              },
              {
                "const": "es-tbai-v1",
                "title": "Spain TicketBAI"
              },
              {
                "const": "es-verifactu-v1",
                "title": "Spain Verifactu V1"
              },
              {
                "const": "eu-en16931-v2017",
                "title": "EN 16931-1:2017"
              },
              {
                "const": "fr-choruspro-v1",
                "title": "Chorus Pro"
              },
              {
                "const": "fr-facturx-v1",
                "title": "French Factur-X v1"
              },
              {
                "const": "gr-mydata-v1",
                "title": "Greece MyData v1.x"
              },
              {
                "const": "it-sdi-v1",
                "title": "Italy SDI FatturaPA v1.x"
              },
              {
                "const": "it-ticket-v1",
                "title": "Italy AdE ticket v1.x"
              },
              {
                "const": "mx-cfdi-v4",
                "title": "Mexican SAT CFDI v4.X"
              },
              {
                "const": "pt-saft-v1",
                "title": "Portugal SAF-T"
              }
            ]
          },
          "type": "array",
          "title": "Addons",
          "description": "Addons defines a list of keys used to identify tax addons that apply special\nnormalization, scenarios, and validation rules to a document."
        },
        "$tags": {
          "items": {
            "$ref": "https://gobl.org/draft-0/cbc/key"
          },
          "type": "array",
          "title": "Tags",
          "description": "Tags are used to help identify specific tax scenarios or requirements that will\napply changes to the contents of the invoice. Tags by design should always be optional,\nit should always be possible to build a valid invoice without any tags."
        },
        "uuid": {
          "type": "string",
          "format": "uuid",
          "title": "UUID",
          "description": "Universally Unique Identifier."
        },
        "type": {
          "$ref": "https://gobl.org/draft-0/cbc/key",
          "oneOf": [
            {
              "const": "purchase",
              "title": "Purchase Order",
              "description": "A purchase order is a document that a buyer sends to a seller to request goods or services."
            },
            {
              "const": "sale",
              "title": "Sales Order",
              "description": "A sales order is a document that a seller sends to a buyer to confirm the sale of goods or services."
            },
            {
              "const": "quote",
              "title": "Quote",
              "description": "A quote is a document that a seller sends to a buyer to provide a price for goods or services."
            }
          ],
          "title": "Type",
          "description": "Type of the order."
        },
        "series": {
          "$ref": "https://gobl.org/draft-0/cbc/code",
          "title": "Series",
          "description": "Series is used to identify groups of orders by date, business area, project,\ntype, customer, a combination of any, or other company specific data.\nIf the output format does not support the series as a separate field, it will be\nprepended to the code for presentation with a dash (`-`) for separation."
        },
        "code": {
          "$ref": "https://gobl.org/draft-0/cbc/code",
          "title": "Code",
          "description": "Code is a sequential identifier that uniquely identifies the order. The code can\nbe left empty initially, but is **required** to **sign** the document."
        },
        "issue_date": {
          "$ref": "https://gobl.org/draft-0/cal/date",
          "title": "Issue Date",
          "description": "When the invoice was created.",
          "calculated": true
        },
        "issue_time": {
          "$ref": "https://gobl.org/draft-0/cal/time",
          "title": "Issue Time",
          "description": "IssueTime is an optional field that may be useful to indicate the time of day when\nthe order was issued. Some regions and formats may require this field to be set.\nAn empty string will be automatically updated to reflect the current time, otherwise\nthe field can be left with a nil value.",
          "calculated": true
        },
        "op_date": {
          "$ref": "https://gobl.org/draft-0/cal/date",
          "title": "Operation Date",
          "description": "Date when the operation defined by the invoice became effective."
        },
        "value_date": {
          "$ref": "https://gobl.org/draft-0/cal/date",
          "title": "Value Date",
          "description": "When the taxes of this invoice become accountable, if none set, the issue date is used."
        },
        "currency": {
          "$ref": "https://gobl.org/draft-0/currency/code",
          "title": "Currency",
          "description": "Currency for all invoice totals.",
          "calculated": true
        },
        "exchange_rates": {
          "items": {
            "$ref": "https://gobl.org/draft-0/currency/exchange-rate"
          },
          "type": "array",
          "title": "Exchange Rates",
          "description": "Exchange rates to be used when converting the invoices monetary values into other currencies."
        },
        "contracts": {
          "items": {
            "$ref": "https://gobl.org/draft-0/org/document-ref"
          },
          "type": "array",
          "title": "Contracts",
          "description": "The identification of contracts."
        },
        "preceding": {
          "items": {
            "$ref": "https://gobl.org/draft-0/org/document-ref"
          },
          "type": "array",
          "title": "Preceding Details",
          "description": "Key information regarding previous order documents."
        },
        "identities": {
          "items": {
            "$ref": "https://gobl.org/draft-0/org/identity"
          },
          "type": "array",
          "title": "Identities",
          "description": "Additional codes, IDs, SKUs, or other regional or custom identifiers that may be used to identify the order."
        },
        "period": {
          "$ref": "https://gobl.org/draft-0/cal/period",
          "title": "Period",
          "description": "Period of time in which the order is valid."
        },
        "tax": {
          "$ref": "https://gobl.org/draft-0/bill/tax",
          "title": "Tax",
          "description": "Special tax configuration for billing."
        },
        "supplier": {
          "$ref": "https://gobl.org/draft-0/org/party",
          "title": "Supplier",
          "description": "The entity supplying the goods or services and usually responsible for paying taxes."
        },
        "customer": {
          "$ref": "https://gobl.org/draft-0/org/party",
          "title": "Customer",
          "description": "Legal entity receiving the goods or services, may be nil in certain circumstances such as simplified invoices."
        },
        "buyer": {
          "$ref": "https://gobl.org/draft-0/org/party",
          "title": "Buyer",
          "description": "Party who is responsible for issuing payment, if not the same as the customer."
        },
        "seller": {
          "$ref": "https://gobl.org/draft-0/org/party",
          "title": "Seller",
          "description": "Seller is the party liable to pay taxes on the transaction if not the same as the supplier."
        },
        "lines": {
          "items": {
            "$ref": "https://gobl.org/draft-0/bill/line"
          },
          "type": "array",
          "title": "Lines",
          "description": "List of lines representing each of the items to be ordered."
        },
        "discounts": {
          "items": {
            "$ref": "https://gobl.org/draft-0/bill/discount"
          },
          "type": "array",
          "title": "Discounts",
          "description": "Discounts or allowances applied to order totals"
        },
        "charges": {
          "items": {
            "$ref": "https://gobl.org/draft-0/bill/charge"
          },
          "type": "array",
          "title": "Charges",
          "description": "Charges or surcharges applied to order totals"
        },
        "payment": {
          "$ref": "https://gobl.org/draft-0/bill/payment-details",
          "title": "Payment Details",
          "description": "Information on when, how, and to whom a final invoice would be paid."
        },
        "delivery": {
          "$ref": "https://gobl.org/draft-0/bill/delivery-details",
          "title": "Delivery Details",
          "description": "Specific details on delivery of the goods to copy to the final invoice."
        },
        "totals": {
          "$ref": "https://gobl.org/draft-0/bill/totals",
          "title": "Totals",
          "description": "Summary of all the order totals, including taxes (calculated).",
          "calculated": true
        },
        "notes": {
          "items": {
            "$ref": "https://gobl.org/draft-0/org/note"
          },
          "type": "array",
          "title": "Notes",
          "description": "Unstructured information that is relevant to the order, such as correction or additional\nlegal details."
        },
        "complements": {
          "items": {
            "$ref": "https://gobl.org/draft-0/schema/object"
          },
          "type": "array",
          "title": "Complements",
          "description": "Additional complementary objects that add relevant information to the order."
        },
        "meta": {
          "$ref": "https://gobl.org/draft-0/cbc/meta",
          "title": "Meta",
          "description": "Additional semi-structured data that doesn't fit into the body of the order."
        },
        "attachments": {
          "items": {
            "$ref": "https://gobl.org/draft-0/org/attachment"
          },
          "type": "array",
          "title": "Attachments",
          "description": "Attachments provide additional information or supporting documents that are not included\nin the main document. It is important that attachments are not used for alternative\nversions of the PDF, for that, see \"links\" inside the envelope headers."
        }
      },
      "type": "object",
      "required": [
        "issue_date",
        "currency",
        "supplier"
      ],
      "description": "Order documents are used for the initial part of a order-to-invoice process where the buyer requests goods or services from the seller.",
      "recommended": [
        "$regime",
        "series",
        "code",
        "lines"
      ]
    }
  }
}

=== invopop/gobl/regimes/co/examples/simple.json
{
  "$schema": "https://gobl.org/draft-0/bill/invoice",
  "uuid": "3aea7b56-59d8-4beb-90bd-f8f280d852a0",
  "code": "1234",
  "series": "SETT",
  "currency": "COP",
  "issue_date": "2021-01-01",
  "supplier": {
    "name": "EXAMPLE SUPPLIER S.A.S.",
    "tax_id": {
      "country": "CO",
      "code": "9014514812"
    },
    "ext": {
      "co-dian-municipality": "11001"
    },
    "addresses": [
      {
        "street": "CRA 8 113 31 OF 703",
        "locality": "Bogot치, D.C.",
        "region": "Bogot치",
        "country": "CO"
      }
    ]
  },
  "customer": {
    "name": "EXAMPLE CUSTOMER S.A.S.",
    "tax_id": {
      "country": "CO",
      "code": "9014514805"
    },
    "ext": {
      "co-dian-municipality": "11001"
    },
    "addresses": [
      {
        "street": "CRA 8 113 31 OF 703",
        "locality": "Bogot치, D.C.",
        "region": "Bogot치",
        "country": "CO"
      }
    ],
    "emails": [
      {
        "addr": "benito.ortiz@example.com"
      }
    ],
    "telephones": [
      {
        "num": "3114131811"
      }
    ]
  },
  "lines": [
    {
      "quantity": "1",
      "item": {
        "name": "Servicios Mes de Julio 2022",
        "price": "200000.00"
      },
      "taxes": [
        {
          "cat": "VAT",
          "percent": "19%"
        }
      ]
    }
  ],
  "payment": {
    "terms": {
      "due_dates": [
        {
          "date": "2021-01-01",
          "percent": "100%"
        }
      ]
    }
  }
}

=== invopop/gobl/examples/co/simplified-id.json
{
  "$schema": "https://gobl.org/draft-0/bill/invoice",
  "$addons": ["co-dian-v2"],
  "uuid": "3aea7b56-59d8-4beb-90bd-f8f280d852a0",
  "code": "1234",
  "series": "SETT",
  "currency": "COP",
  "issue_date": "2021-01-01",
  "tax": {
    "tags": ["simplified"]
  },
  "supplier": {
    "tax_id": {
      "country": "CO",
      "code": "9014514812"
    },
    "name": "EXAMPLE SUPPLIER S.A.S.",
    "ext": {
      "co-dian-municipality": "11001",
      "co-dian-fiscal-responsibility": "O-23"
    }
  },
  "customer": {
    "name": "Test end user",
    "identities": [
      {
        "key": "co-id-card",
        "code": "1234567890"
      }
    ]
  },
  "lines": [
    {
      "quantity": "1",
      "item": {
        "name": "Useful service",
        "price": "200000.00"
      },
      "taxes": [
        {
          "cat": "VAT",
          "percent": "19%"
        }
      ]
    }
  ],
  "payment": {
    "advances": [
      {
        "desc": "Prepaid",
        "percent": "100%"
      }
    ]
  }
}

=== invopop/gobl/examples/es/invoice-es-es-verifactu-simplified-with-customer.json
{
  "$schema": "https://gobl.org/draft-0/bill/invoice",
  "$addons": ["es-verifactu-v1"],
  "$tags": ["simplified"],
  "uuid": "3aea7b56-59d8-4beb-90bd-f8f280d852a1",
  "currency": "EUR",
  "issue_date": "2024-12-04",
  "series": "SAMPLE",
  "code": "005",
  "supplier": {
    "tax_id": {
      "country": "ES",
      "code": "B98602642"
    },
    "name": "Provide One S.L.",
    "emails": [
      {
        "addr": "billing@example.com"
      }
    ],
    "addresses": [
      {
        "num": "42",
        "street": "Calle Pradillo",
        "locality": "Madrid",
        "region": "Madrid",
        "code": "28002",
        "country": "ES"
      }
    ]
  },
  "customer": {
    "tax_id": {
      "country": "ES",
      "code": "54387763P"
    },
    "name": "Sample Consumer"
  },
  "lines": [
    {
      "quantity": "20",
      "item": {
        "name": "Development services",
        "price": "90.00",
        "unit": "h"
      },
      "taxes": [
        {
          "cat": "VAT",
          "rate": "standard"
        }
      ]
    },
    {
      "quantity": "1",
      "item": {
        "name": "Other service",
        "price": "10.00"
      },
      "taxes": [
        {
          "cat": "VAT",
          "rate": "standard"
        }
      ]
    }
  ]
}

=== invopop/gobl/examples/br/invoice-nfse.json
{
  "$schema": "https://gobl.org/draft-0/bill/invoice",
  "$addons": [
    "br-nfse-v1"
  ],
  "uuid": "0193305c-a7be-730d-b552-2093f0df2df7",
  "series": "SAMPLE",
  "code": "1",
  "issue_date": "2024-11-15",
  "currency": "BRL",
  "supplier": {
    "name": "SaúdeMais Serviços Médicos Ltda.",
    "tax_id": {
      "country": "BR",
      "code": "55263640000186"
    },
    "identities": [
      {
        "key": "br-nfse-municipal-reg",
        "code": "45678901234567"
      }
    ],
    "addresses": [
      {
        "num": "200",
        "street": "Rua Primeiro de Março",
        "street_extra": "Torre A",
        "locality": "Centro",
        "region": "Rio de Janeiro",
        "state": "RJ",
        "code": "20010-000",
        "country": "BR"
      }
    ],
    "emails": [
      {
        "addr": "saudemais@example.com"
      }
    ],
    "ext": {
      "br-ibge-municipality": "3304557",
      "br-nfse-fiscal-incentive": "1",
      "br-nfse-simples": "1",
      "br-nfse-special-regime": "4"
    }
  },
  "customer": {
    "name": "Construforte Engenharia Ltda.",
    "tax_id": {
      "country": "BR",
      "code": "46602178000103"
    },
    "addresses": [
      {
        "num": "75",
        "street": "Avenida Sete de Setembro",
        "street_extra": "Bloco C",
        "locality": "Centro",
        "region": "Salvador",
        "state": "BA",
        "code": "40060-000",
        "country": "BR"
      }
    ]
  },
  "lines": [
    {
      "i": 1,
      "quantity": "15",
      "item": {
        "name": "Consultancy Services",
        "price": "100.00",
        "ext": {
          "br-nfse-service": "10.5",
          "br-nfse-cnae": "62.01-5-01"
        }
      },
      "taxes": [
        {
          "cat": "ISS",
          "percent": "15%",
          "ext": {
            "br-nfse-iss-liability": "1"
          }
        }
      ]
    }
  ]
}
